- .github/GITHUB_REPO_LABELS_TEMPLATE.yml
- .github/workflows/sync_github_repo_labels.yml
> [#1][INFRA] 레이블 싱크 깃헙 액션 및 레이블 템플릿 추가

- README.md
- nuxt.config.js
- package.json
- vue-shim.d.ts
- yarn.lock
- 수정이유: Typescript 환경 맞춤 파일 전환 및 decorator 설치
- 수정내용: Typescript 모듈 및 Lint, nuxt-property-decorator 설치
- resolved: #3 
> [#3][INFRA] Typescript 환경 적용 및 README.md 수정

- components/layouts.default/MainFooter.vue
- components/pages.index/Carousel.vue
- pages/index.vue
- 수정이유: 모바일 환경에서 화면상 컴포넌트가 제 위치(중심)를 잘 잡지 못함
- 수정내용: <v-row> -> <v-container> 변경 후 class 수정
- resolved: #15
> [#15][FIX] index.vue의 최상위 부모 태그 수정 및 Timeline.vue css 일부 수정

- components/pages.service.easyxplain.achievements/CardList.vue
- components/pages.service.easyxplain.introduce/HowToUseCards.vue
- pages/service/easyxplain/achievements.vue
- pages/service/easyxplain/introduce.vue
- 수정이유: 업적 이미지 출력이 정상적이지 않은 문제 해결
- 수정내용: v-list-item-avatar 활용 구조 변경 및 기타 class 수정
- resolved: #11
> [#11][STYLE][FIX] avatar image 출력 수정 및 text 정렬, 여백 수정

- nuxt.config.ts
- package.json
- yarn.lock
- 수정이유: 페이지 방문자 정보 수집 필요
- 수정내용: @nuxtjs/google-analytics 추가 및 속성 부여
- resolved: #29
> [#29][FEATURE] Google Analytics for nuxt 추가

- components/layouts.default/TopBar.vue
- layouts/default.vue
> [#31][FEATURE][REFACTOR] TopBar.vue 추가

- components/layouts.default/TopBar.vue
- components/pages.index/Services.vue
- components/pages.index/Timeline.vue
- components/pages.service.easyxplain.introduce/Carousel.vue
- components/pages.service.easyxplain.introduce/Differentiation.vue
- components/pages.service.easyxplain.introduce/Timeline.vue
- pages/index.vue
- pages/service/easyxplain/introduce.vue
- 수정이유: Window 환경에서 폰트 가독성 나쁨
- 수정내용: font-size 변경 및 기타 디자인 디테일 수정
- resolved: #34
> [#34][STYLE][FEATURE] CSS 디테일 수정

- nuxt.config.ts
- static/robots.txt
- static/sitemap.xml
- 수정이유: 서비스 소개도 포함하므로 검색이 수월해야 함
- 수정내용: sitemap.xml & robots.txt 및 SearchConsole 인증 태그 삽입
- resolved: #39
> [#39][DOC] sitemap.xml & robots.txt 및 SearchConsole 인증

- jwt-creation-app-for-knowease-inc-github-io/README.md
- pages/service/easyxplain/introduce.vue
- 수정이유: 수정 후 미처 삭제하지 못한 내용, 반영하지 못한 스캐폴딩 구조가 있음
- 수정내용: ./pages/service/easyxplain/introduce.vue 내 html 일부 삭제
- 세부내용: README 내 'Components using this API' 수정
- resolved: #44
> [#44][FIX][DOC] 잘못된 html 태그 삭제, 변화된 스캐폴딩 구조 README.md 반영

- components/pages.index/Founders.vue
- 수정이유: '자문'역 표기가 되어있지 않으면 여러 오해가 발생할 수 있습니다
- 수정내용: 팀 멤버와 자문역 분할 표기
- resolved: #81
> [#81][FIX][STYLE] 함께하는 사람들에 '자문'역 표기

- components/pages.index/Carousel.vue
- pages/service/easyxplain/introduce.vue
> [#84][FIX][STYLE] 출력되지 않는 이미지 cdn 주소 교체, 소개 페이지 구조 변경

- .github/workflows/cd.yml
- .github/workflows/sync_github_repo_labels.yml
> [#98][DOC][FIX] Github Actions yml 기준 브랜치를 main 으로 변경

- components/layouts.default/TopBar.vue
- components/pages.recruit/RecruitInfos.vue
- nuxt.config.ts
- pages/recruit/index.vue
- pages/service/meaniit/introduce.vue
> [#123][FEATURE][DOC] 2023년 2월 웹개발자 채용공고문 추가 

- components/pages.recruit/RecruitInfos.vue
- pages/recruit/index.vue
- 수정 이유: 지원자 입장에서 중요한 정보 추가
- 수정 내용: 100% 재택근무, 유연 근무, 채용 경향 추가
- resolved: #123
> [#123][DOC] 100% 재택근무, 유연 근무 추가

- pages/recruit/index.vue
- 수정이유: 채용인원 정보도 필요합니다
- 수정내용: '채용 인원: 1명' 정보를 추가했습니다
- resolved: #123
> [#123][DOC] 웹개발자(프론트엔드) 채용 인원 1명 추가

- components/pages.index/Founders.vue
- yarn.lock
- 수정이유: 신규 입사
- 수정내용: 신규 입사자 링크드인 뱃지 추가, 뱃지 레이아웃 변경
- resolved: #131
> [#131][FE] 신규 입사자 링크드인 게재

- pages/service/meaniit/extension-meaniit.vue
> [#137][FEATURE] PC, 태블릿, 모바일 기초 반응형 대응

- pages/service/meaniit/extension-meaniit.vue
> [#139][FIX] 모바일 환경에서 최하단부 footer 겹침, font-size 해결

- pages/service/meaniit/extension-meaniit.vue
- 수정이유: 어떤 환경에서 정상동작하는지 사용자가 알아야함
- 수정내용: Chrome 브라우저에서 정상동작, 기능 사용 직후 탭 이동 시 에러가능성 추가
- resolved: #141
> [#141][FEATURE] 유의사항 문구 추가: Chrome 브라우저 사용 안내

- static/navere102e96b2e1c22eb64a7f820e7478a47.html
- 수정이유: 네이버의 '사이트 소유확인' 파일 필요
- 수정내용: `./static/` 내에 해당 파일 추가 (from NAVER)
- resolved: #144
> [#144][FEATURE] 네이버 사이트 소유확인 파일 업로드

- components/pages.service.meaniit.introduce/TopIntro.vue
- pages/privacy-policy.vue
> [#160][DOC][FIX] '서비스 소개' 전면의 서비스 설명 수정

- components/pages.index/Founders.vue
- 수정이유: 신규 입사 및 카드 내 내용물 겹침 현상 수정
- 수정내용: 신규 입사자 정보 추가, 프로필 카드 내/외부 간격 조정
- resolved: #172
> [#172][FEATURE][FIX] 신규 입사자 추가, 프로필 카드 조정

- components/layouts.default/TopBar.vue
- components/pages.index/Founders.vue
- pages/recruit/index.vue
> [#174][FEATURE][FIX] 백엔드 채용공고 마감 및 프로필 카드 이미지 출력 에러 수정 

- components/pages.index/Timeline.vue
- components/pages.service.meaniit.introduce/Timeline.vue
- resolved: #182 
- 회사 소개페이지 및 서비스 페이지 내 '연혁'에 새 연혁 추가
- 웹, 모바일 모두 적용
- TBD
- TBD
> [#182][FEATURE] 서비스 소개 페이지 연혁 추가: 2024.4 파일럿 프로그램 진행

- components/pages.index/Services.vue
- 수정이유: 견본 및 파일럿 프로그램 진행중으로 서비스 '바로가기'로 변경 필요
- 수정내용: '(진행중)' -> '바로가기' 수정 및 링크 추가
- resolved: #186
- (진행중)이 '바로가기'로 표시되며, 클릭 시 홈페이지로 이동
- TBD
- TBD
> [#186][FEATURE] '(진행중)' -> '바로가기' 수정 및 링크 추가

- components/pages.index/Partners.vue
- pages/index.vue
- 수정이유: 배치 조정 및 불필요한 소제목 삭제 필요
- 수정내용: 데스크탑 CI 2줄 배치로 변경, 소제목 삭제
- resolved: #190 
- TBD
- TBD
> [#190][FEATURE] 고객사 CI 배치 방식 조정 및 소제목 삭제

- .github/workflows/cd.yml
- 수정이유: 배포 실패 발생
- 수정내용: node 버전을 마이그레이션 이후 로컬 버전과 통일
- 세부내용: node version 14 -> 20.9.0
- resolved: #199
- Github Actions 통한 배포 성공이 되어야합니다
- 배포 실패 재발생
- node 버전 표기 재확인
> [#199][FIX][INFRA] node 버전 수정

- components/pages.index/Carousel.vue
- 수정이유: 배포 후 이미지 에러 발생
- 수정내용: 해당 이미지 경로 수정(->절대경로)
- resolved: #201
- TBD
- TBD
- TBD
> [#201][FIX] 배포 후 이미지 에러 발생

- .github/workflows/cd.yml
- components/layouts.default/MainFooter.vue
- components/layouts.default/TopBar.vue
- components/pages.index/Carousel.vue
- components/pages.index/Services.vue
- components/pages.index/Timeline.vue
- composables/useGA4.js
- layouts/default.vue
- package.json
- yarn.lock
- resolved: #197
- 기존 사용자 행동 분석 방식(UA) 제거
- 구글 애널리틱스(GA4) 이벤트 연결 및 커스텀 이벤트 트리거
- TBD
- TBD
> [#197][FEATURE] 사용자 행동 분석 방식 변경 및 구글 애널리틱스(GA4) 이벤트 적용

- nuxt.config.ts
- 수정이유: 마이그레이션 이전 config 파일
- 수정내용: config 파일 마이그레이션 내용 적용 및 ga4 설정
- resolved: #206
- TBD
- TBD
- TBD
> [#206][FEATURE][FIX] GA4 설정 수정(nuxt.config)

- composables/useGA4.js
- nuxt.config.ts
- 수정이유: 배포된 사이트와 GA4 연결 필요
- 수정내용: 불필요한 환경변수 제거 후 ga4 측정 ID 직접 할당
- resolved: #208
- TBD
- TBD
- TBD
> [#208][FIX] 배포된 사이트와 ga4 연결 안되는 에러

- README.md
- components/pages.service.meaniit.voiceofcustomer/vocIssueInputForm.vue
- nuxt.config.ts
- package.json
- pages/recruit/index.vue
- pages/service/meaniit/introduce.vue
- public/robots.txt
- public/sitemap.xml
- 수정이유: 설정된 SEO 최적화 필요
- 수정내용: 기존 설정된 SEO 수정 및 추가, 미사용 페이지 SEO 삭제
- 세부사항:
- robots.txt: 불필요한 크롤러 삭제
- sitemap.xml: 미사용 페이지 삭제 및 다국어 페이지 추가
- 각 페이지: 전역 설정 외 페이지 별 seo 설정 항목 수정
- nuxt.config 및 package.json: 구글 search console 값 변경 및 회사 도메인 수정 등
- resolved: #210
- TBD
- google search console 연결 에러로 SEO 설정 확인 불가한 상황
- google search console 연결 에러 해결
> [#210][REFACTOR] SEO 최적화

- nuxt.config.ts
- public/google969c822df4856397.html
- 수정이유: 사용자 별 메타 값이 상이해 대표자의 변경되지 않는 인증방식 필요
- 수정내용: 'html 태그' -> 'html 파일' 인증방식으로 변경
- resolved: #212
- TBD
- TBD
- TBD
> [#212][REFACTOR] SEO 확인을 위한 Google Search Console 인증 방식 변경

- components/pages.index/Contact.vue
- components/pages.index/Founders.vue
- components/pages.index/HeroSection.vue
- components/pages.index/Services.vue
- locales/en.json
- locales/ko.json
- 수정이유: 배포된 사이트 에러에 대한 검증 중 발견된 문제 해결
- 수정내용: i18n사용시 v-html에 사용된 <br/>삭제, 이메일(@) 표기법 변경, 바인딩 오류 수정
- resolved: #225
- TBD
- 배포시 500 에러 미해결
- 폰트 관련 내용 확인 필요
> [#225][FIX] 로컬 실행시 발생한 warning 및 error 해결

- components/layouts.default/MainFooter.vue
- components/layouts.default/TopBar.vue
- components/pages.index/Contact.vue
- components/pages.index/Founders.vue
- components/pages.index/HeroSection.vue
- components/pages.index/Partners.vue
- components/pages.index/Services.vue
- components/pages.index/Timeline.vue
- composables/useGA4.js
- layouts/default.vue
- nuxt.config.ts
- resolved: #242
- 문의사항 등록시 유효성 검사 정상 진행, 관련 메세지 정상 렌더링
- ga4 이벤트 감지 확인
- TBD
- TBD
> [#242][FIX] '문의사항' 등록시 오류 해소 및 안내 문구 추가, GA4 이벤트 수정 및 추가

- components/pages.index/Contact.vue
- components/pages.index/Services.vue
- nuxt.config.ts
- 수정이유: UX향상을 위해
- 수정내용: 로딩 UI 추가, 메세지 표시 스타일 변경, ga4 속성 변경
- resolved: #245
- 사용자 액션 발생시 에러문구 스타일
- 로딩 미진행, 중복 이메일 에러 표시 등
- 배포 후 통신 확인 필요
> [#245][FIX] 문의사항 등록 컴포넌트 UI/UX 수정 및 GA4 속성 변경

- layouts/default.vue
- locales/ko.json
- nuxt.config.ts
- 수정이유: Google Ads snippet 미동작
- 수정내용: Google Ads snippet을 스크립트 내 useHead로 이동
- 세부내용:
- description에 포함된 <br /> 제거
- resolved: #249
- TBD
- TBD
- TBD
> [#249][FEATURE][FIX] Google Ads snippet 미동작
